LaBucaDeiDiavoli/Models/Articoli.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LaBucaDeiDiavoli.Models
{
    public class Articoli
    {
        [Key]
        public int IdArticolo { get; set; }
        public string Nome { get; set; }
        public string Immagine { get; set; }
        
        public decimal Prezzo { get; set; }
        public int TempoConsegna { get; set; }
    }
}

LaBucaDeiDiavoli/Controllers/ArticoliController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using LaBucaDeiDiavoli.Models;

namespace LaBucaDeiDiavoli.Controllers
{
    [Authorize]
    public class ArticoliController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        

        // GET: Articoli
        public ActionResult Index()
        {
            var isUserAdmin = User.IsInRole("Admin");
            ViewBag.IsUserAdmin = isUserAdmin;
            return View(db.Articoli.ToList());
        }

        // GET: Articoli/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articoli articoli = db.Articoli.Find(id);
            if (articoli == null)
            {
                return HttpNotFound();
            }
            return View(articoli);
        }

        //[Authorize(Roles="Admin")]

        // GET: Articoli/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Articoli/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public ActionResult Create(Articoli articoli, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var extension = Path.GetExtension(file.FileName).ToLower();
                    if (extension != ".jpg" && extension != ".png" && extension != ".gif" && extension != ".jpeg")
                    {
                        ModelState.AddModelError("", "Il file caricato non è un'immagine valida. Sono accettate solo immagini .jpg, .png, .gif, .jpeg");
                        return View(articoli);
                    }

                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/image"), fileName);
                    file.SaveAs(path);
                    articoli.Immagine = fileName;
                }
                db.Articoli.Add(articoli);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articoli);
        }


       // [Authorize(Roles="Admin")]

        // GET: Articoli/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articoli articoli = db.Articoli.Find(id);
            if (articoli == null)
            {
                return HttpNotFound();
            }
            return View(articoli);
        }

        // POST: Articoli/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdArticolo,Nome,Immagine,Prezzo,TempoConsegna")] Articoli articoli)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articoli).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articoli);
        }


        [Authorize(Roles="Admin")]
        // GET: Articoli/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articoli articoli = db.Articoli.Find(id);
            if (articoli == null)
            {
                return HttpNotFound();
            }
            return View(articoli);
        }

        // POST: Articoli/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articoli articoli = db.Articoli.Find(id);
            db.Articoli.Remove(articoli);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
        

        //[Authorize(Roles="User")]
        [HttpPost]
        
        public ActionResult AddToCart(int productId, int quantity)
        {
           
            var user = db.Utenti.FirstOrDefault(u => u.Username == User.Identity.Name);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Utente non trovato");
            }

            
            var order = db.Ordini.SingleOrDefault(o => o.IdUtente == user.IdUtente && !o.IsEvaso);

          
            if (order == null)
            {
                order = new Ordini { IdUtente = user.IdUtente, IsEvaso = false, DettagliOrdini = new List<DettagliOrdini>(), DataOrdine = DateTime.Now };
                db.Ordini.Add(order);
            }

           
            var orderDetail = order.DettagliOrdini.FirstOrDefault(d => d.Articoli.IdArticolo == productId);

            if (orderDetail != null)
            {
                orderDetail.Quantita += quantity;
                orderDetail.PrezzoTotale = orderDetail.Articoli.Prezzo * orderDetail.Quantita;

            }
            else
            {
               
                var product = db.Articoli.Find(productId);
                if (product == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Prodotto non trovato");
                }
                order.DettagliOrdini.Add(new DettagliOrdini { Articoli = product, Quantita = quantity, PrezzoTotale = product.Prezzo * quantity });
            }

            try
            {
                db.SaveChanges();
                TempData["SuccessMessage"] = "Prodotto aggiunto al carrello con successo!";
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
                TempData["ErrorMessage"] = "Errore durante il salvataggio dei dati";
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles="User")]
        public ActionResult Cart()
        {
            // Recupera il carrello dalla sessione
            var cart = Session["cart"] as List<Articoli> ?? new List<Articoli>();

            return View(cart);
        }





    }
}

LaBucaDeiDiavoli/Views/Articoli/Cart.cshtml
@model IEnumerable<LaBucaDeiDiavoli.Models.Articoli>

@{
    ViewBag.Title = "Cart";
}

<h2>Cart</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Immagine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezzo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Immagine)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezzo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TempoConsegna)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdArticolo }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdArticolo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdArticolo })
        </td>
    </tr>
}

</table>

LaBucaDeiDiavoli/Views/Articoli/Create.cshtml
@model LaBucaDeiDiavoli.Models.Articoli

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Articoli</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Immagine, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Immagine" />
            @Html.ValidationMessageFor(model => model.Immagine, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TempoConsegna, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TempoConsegna, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TempoConsegna, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LaBucaDeiDiavoli/Views/Articoli/Delete.cshtml
@model LaBucaDeiDiavoli.Models.Articoli

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Articoli</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Immagine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Immagine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempoConsegna)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LaBucaDeiDiavoli/Views/Articoli/Details.cshtml
@model LaBucaDeiDiavoli.Models.Articoli

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Articoli</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Immagine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Immagine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempoConsegna)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdArticolo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LaBucaDeiDiavoli/Views/Articoli/Edit.cshtml
@model LaBucaDeiDiavoli.Models.Articoli

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Articoli</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdArticolo)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Immagine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Immagine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Immagine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempoConsegna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempoConsegna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempoConsegna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LaBucaDeiDiavoli/Views/Articoli/Index.cshtml
@model IEnumerable<LaBucaDeiDiavoli.Models.Articoli>

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        body {
            background-image: url('../../Content/image/sfondopizza.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }

        .card-img-top {
            width: 100%;
            max-height: 200px;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Aggiungi Un Prodotto", "Create")
    </p>

    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-4">
                    <div class="card" style="width: 18rem;">
                        <img src="@Url.Content("~/Content/Image/" + item.Immagine)" style="height:285px; width:285px" class="card-img-top" alt="@item.Nome">
                        <div class="card-body">
                            <h5 class="card-title">@item.Nome</h5>
                            <p class="card-text">Prezzo: @item.Prezzo</p>
                            <p class="card-text">Tempo di consegna: @item.TempoConsegna</p>
                            <input type="number" min="1" id="quantity-@item.IdArticolo" value="1">
                            <form action="@Url.Action("AddToCart", "Articoli")" method="post">
                                <input type="hidden" name="id" value="@item.IdArticolo" />
                                <input type="submit" value="Aggiungi al carrello" class="btn btn-primary" />
                            </form>

                            <a href="@Url.Action("Edit", new { id = item.IdArticolo })" class="btn btn-primary">Edit</a>
                            <a href="@Url.Action("Details", new { id = item.IdArticolo })" class="btn btn-primary">Details</a>
                            <a href="@Url.Action("Delete", new { id = item.IdArticolo })" class="btn btn-danger">Delete</a>
                           
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>